version: '3'
services:
    chatbot:
        image: rasa/rasa:1.10.10-full
        container_name: chatbot-rasa
        ports:
            - 5005:5005
            - 443:443
        volumes:
            - ./:/app
        networks: 
            - production-network
        command: run
    actions:
        image: rasa/rasa:1.10.10-full
        container_name: actions-rasa
        environment: 
            - PYTHONUNBUFFERED=1
        ports:
            - 5055:5055
        volumes:
            - ./:/app
        networks: 
            - production-network
        command: run actions
    # trainer:
    #     image: rasa/rasa:1.10.10-full
    #     container_name: trainer-rasa
    #     volumes:
    #         - ./:/app
    #     command: train
    duckling:
        image: rasa/duckling:latest
        container_name: duckling-rasa
        ports:
            - 8000:8000
        networks: 
            - production-network
networks: 
    production-network:
        driver: bridge